# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-05 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20190105_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='specialist',
            new_name='employee',
        ),
    ]
