# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-03 21:10
from __future__ import unicode_literals

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20181203_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=django_google_maps.fields.AddressField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
