# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-06 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20181206_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='latitude',
            field=models.DecimalField(decimal_places=30, max_digits=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='longitude',
            field=models.DecimalField(decimal_places=30, max_digits=50),
        ),
    ]
