# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-30 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20181230_1813'),
        ('company', '0009_auto_20181230_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='procedure',
            field=models.ManyToManyField(related_name='procedures', to='service.Service', verbose_name='procedures'),
        ),
    ]
