# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-31 17:29
from __future__ import unicode_literals

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_company_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True),
        ),
    ]
