# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-31 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20181231_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='procedure',
            new_name='procedures',
        ),
    ]
