# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-03 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20181231_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='region',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
