# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-05 20:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_company_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Заклад', 'verbose_name_plural': 'Заклади'},
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/logos', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Послуга'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Category', verbose_name='Батьківська категорія'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='company',
            name='house_number',
            field=models.IntegerField(verbose_name='Номер будинку'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='company',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=30, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='images/logos', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='company',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=30, verbose_name='Довгота'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_owner', to=settings.AUTH_USER_MODEL, verbose_name='Власник'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='company',
            name='procedures',
            field=models.ManyToManyField(related_name='procedures', to='service.Service', verbose_name='Послуги'),
        ),
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(max_length=255, verbose_name='Регіон'),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='company',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Вулиця'),
        ),
    ]
