# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-06 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20190105_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/pictures', verbose_name='Зображення')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='pictures',
            field=models.ManyToManyField(to='company.Picture', verbose_name='Зображення'),
        ),
    ]
