# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-06 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20190106_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'Зображення', 'verbose_name_plural': 'Зображення'},
        ),
        migrations.AlterField(
            model_name='company',
            name='procedures',
            field=models.ManyToManyField(blank=True, related_name='procedures', to='service.Service', verbose_name='Послуги'),
        ),
    ]
