# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-28 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_auto_20190106_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='procedures',
            new_name='services',
        ),
    ]
