# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-28 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_auto_20190128_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='services', to='service.Service', verbose_name='Послуги'),
        ),
    ]
