# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-02 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_assign', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assigment',
            options={'verbose_name': 'assigment', 'verbose_name_plural': 'assigments'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'feedback', 'verbose_name_plural': 'feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
