# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-26 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assigment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'assigment',
                'verbose_name_plural': 'assigments',
            },
        ),
    ]
