# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-26 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
        ('company', '0001_initial'),
        ('assigment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigment_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assigment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AddField(
            model_name='assigment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigment_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assigment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service'),
        ),
    ]
