# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-05 20:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assigment', '0002_auto_20180926_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assigment',
            options={'verbose_name': 'Запис', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterField(
            model_name='assigment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigment_client', to=settings.AUTH_USER_MODEL, verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='assigment',
            name='comment',
            field=models.TextField(verbose_name='Додатково'),
        ),
        migrations.AlterField(
            model_name='assigment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Заклад'),
        ),
        migrations.AlterField(
            model_name='assigment',
            name='datetime',
            field=models.DateTimeField(verbose_name='Час'),
        ),
        migrations.AlterField(
            model_name='assigment',
            name='duration',
            field=models.TimeField(verbose_name='Тривалість'),
        ),
        migrations.AlterField(
            model_name='assigment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigment_employee', to=settings.AUTH_USER_MODEL, verbose_name='Працівник'),
        ),
        migrations.AlterField(
            model_name='assigment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service', verbose_name='Послуга'),
        ),
    ]
