# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-05 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20190105_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Персонал сайту'),
        ),
    ]
