export const SEARCH_COMPANY_START = 'SEARCH_COMPANY_START';
export const SEARCH_COMPANY = 'SEARCH_COMPANY';
export const SEARCH_COMPANY_RESULT = 'SEARCH_COMPANY_RESULT';
export const SEARCH_COMPANY_END = 'SEARCH_COMPANY_END';
export const SEARCH_COMPANY_SELECT = 'SEARCH_COMPANY_SELECT';
export const SEARCH_COMPANY_RESET = 'SEARCH_COMPANY_RESET';