# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-21 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20190105_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='assessment',
            new_name='rating',
        ),
    ]
