# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-21 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20190121_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(verbose_name='Оцінка'),
        ),
    ]
